USE MundialClubes
SELECT * FROM USUARIOS
select * from equipo
SELECT * FROM PARTIDO
SELECT * FROM FASE

UPDATE USUARIOS
SET U_PASSWORD='000'
WHERE U_CODIGO=12

CREATE TABLE FASE
(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(50)
)
INSERT INTO FASE
VALUES
('FASE DE GRUPOS'),
('OCTAVOS DE FINAL'),
('CUARTOS DE FINAL'),
('SEMIFINAL'),
('FINAL')

ALTER TABLE EQUIPO
ADD URL_BANDERA VARCHAR(MAX);

ALTER TABLE PARTIDO
ADD FECHA DATETIME;
ALTER TABLE PARTIDO
ADD ID_FASE INT;
ALTER TABLE PARTIDO
ADD C_GRUPO CHAR(1)
ALTER TABLE PARTIDO
ADD FOREIGN KEY (ID_FASE) REFERENCES FASE(ID);

INSERT INTO EQUIPO
VALUES('CA','1','CATAR')
INSERT INTO EQUIPO
VALUES('EC','2','ECUADOR')
INSERT INTO EQUIPO
VALUES('SE','3','SENEGAL')
INSERT INTO EQUIPO
VALUES('PB','4','PAISES BAJOS')
INSERT INTO EQUIPO
VALUES('EN','5','INGLATERRA')
INSERT INTO EQUIPO
VALUES('IR','6','IRAN')
UPDATE EQUIPO
SET URL_BANDERA='https://flagcdn.com/40x30/qa.png'
WHERE C_EQUIPO='CA'
UPDATE EQUIPO
SET URL_BANDERA='https://flagcdn.com/40x30/ec.png'
WHERE C_EQUIPO='EC'
UPDATE EQUIPO
SET URL_BANDERA='https://flagcdn.com/40x30/gb-eng.png'
WHERE C_EQUIPO='EN'
UPDATE EQUIPO
SET URL_BANDERA='https://flagcdn.com/40x30/ir.png'
WHERE C_EQUIPO='IR'
UPDATE EQUIPO
SET URL_BANDERA='https://flagcdn.com/40x30/nl.png'
WHERE C_EQUIPO='PB'
UPDATE EQUIPO
SET URL_BANDERA='https://flagcdn.com/40x30/sn.png'
WHERE C_EQUIPO='SE'

INSERT INTO PARTIDO
(NRO_PARTIDO,C_EQUIPO_1,C_EQUIPO_2,Q_GOLES_E1,Q_GOLES_E2)
VALUES(1,'CA','EC',0,0)
INSERT INTO PARTIDO
(NRO_PARTIDO,C_EQUIPO_1,C_EQUIPO_2,Q_GOLES_E1,Q_GOLES_E2)
VALUES(2,'SE','PB',0,0)
INSERT INTO PARTIDO
(NRO_PARTIDO,C_EQUIPO_1,C_EQUIPO_2,Q_GOLES_E1,Q_GOLES_E2)
VALUES(3,'CA','SE',0,0)
INSERT INTO PARTIDO
(NRO_PARTIDO,C_EQUIPO_1,C_EQUIPO_2,Q_GOLES_E1,Q_GOLES_E2)
VALUES(4,'PB','CA',0,0)	
UPDATE PARTIDO SET FECHA='2022-11-20 10:00:00', ID_FASE=1
WHERE NRO_PARTIDO=1
UPDATE PARTIDO SET FECHA='2022-11-21 10:00', ID_FASE=1
WHERE NRO_PARTIDO=2
UPDATE PARTIDO SET FECHA='2022-11-25 07:00', ID_FASE=1
WHERE NRO_PARTIDO=3
UPDATE PARTIDO SET FECHA='2022-11-25 10:00', ID_FASE=1
WHERE NRO_PARTIDO=4

SP_HELP'PARTIDO'
