// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mundial2022.Entidades;

namespace Mundial2022.Migrations
{
    [DbContext(typeof(MundialClubesContext))]
    [Migration("20220820182838_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mundial2022.Entidades.AjustesPuntaje", b =>
                {
                    b.Property<int>("AId")
                        .HasColumnType("int")
                        .HasColumnName("A_ID");

                    b.Property<int?>("APuntajeEmpate")
                        .HasColumnType("int")
                        .HasColumnName("A_PUNTAJE_EMPATE");

                    b.Property<int?>("APuntajeVictoria")
                        .HasColumnType("int")
                        .HasColumnName("A_PUNTAJE_VICTORIA");

                    b.HasKey("AId")
                        .HasName("PK__AJUSTES___71AC6D41E5C82299");

                    b.ToTable("AJUSTES_PUNTAJE");
                });

            modelBuilder.Entity("Mundial2022.Entidades.ApuestasUsuario", b =>
                {
                    b.Property<string>("NroApuetas")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("NRO_APUETAS")
                        .IsFixedLength(true);

                    b.Property<int>("NroPartido")
                        .HasColumnType("int")
                        .HasColumnName("NRO_PARTIDO");

                    b.Property<string>("UCodigo")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("U_CODIGO")
                        .IsFixedLength(true);

                    b.Property<int?>("APuntosCanjeados")
                        .HasColumnType("int")
                        .HasColumnName("A_PUNTOS_CANJEADOS");

                    b.Property<int?>("AResultadoE1")
                        .HasColumnType("int")
                        .HasColumnName("A_RESULTADO_E1");

                    b.Property<int?>("AResultadoE2")
                        .HasColumnType("int")
                        .HasColumnName("A_RESULTADO_E2");

                    b.Property<int?>("ATipoResultado")
                        .HasColumnType("int")
                        .HasColumnName("A_TIPO_RESULTADO");

                    b.HasKey("NroApuetas", "NroPartido", "UCodigo")
                        .HasName("PK__APUESTAS__EF7BBDE27E7DEF11");

                    b.HasIndex("NroPartido");

                    b.HasIndex("UCodigo");

                    b.ToTable("APUESTAS_USUARIOS");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Campeonato", b =>
                {
                    b.Property<string>("CCampeonato")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_CAMPEONATO")
                        .IsFixedLength(true);

                    b.Property<string>("NCampeonato")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("N_CAMPEONATO");

                    b.Property<int?>("QPartidos")
                        .HasColumnType("int")
                        .HasColumnName("Q_PARTIDOS");

                    b.HasKey("CCampeonato")
                        .HasName("PK__CAMPEONA__0F26C2A815FF9A47");

                    b.ToTable("CAMPEONATO");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Equipo", b =>
                {
                    b.Property<string>("CEquipo")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("C_EQUIPO")
                        .IsFixedLength(true);

                    b.Property<string>("ENombre")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("E_NOMBRE");

                    b.Property<string>("NEquipo")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("N_EQUIPO");

                    b.HasKey("CEquipo")
                        .HasName("PK__EQUIPO__93A80846780A110A");

                    b.ToTable("EQUIPO");
                });

            modelBuilder.Entity("Mundial2022.Entidades.EquiposCampeonato", b =>
                {
                    b.Property<int>("ECId")
                        .HasColumnType("int")
                        .HasColumnName("E_C_ID");

                    b.Property<string>("CEquipo")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("C_EQUIPO")
                        .IsFixedLength(true);

                    b.Property<string>("CCampeonato")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_CAMPEONATO")
                        .IsFixedLength(true);

                    b.Property<int?>("ETotalPuntos")
                        .HasColumnType("int")
                        .HasColumnName("E_TOTAL_PUNTOS");

                    b.HasKey("ECId", "CEquipo", "CCampeonato")
                        .HasName("PK__EQUIPOS___B5F0BEEFDCC47046");

                    b.HasIndex("CCampeonato");

                    b.HasIndex("CEquipo");

                    b.ToTable("EQUIPOS_CAMPEONATO");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Estadio", b =>
                {
                    b.Property<string>("CEstadio")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_ESTADIO")
                        .IsFixedLength(true);

                    b.Property<string>("NEstadio")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("N_ESTADIO");

                    b.HasKey("CEstadio")
                        .HasName("PK__ESTADIO__45173E5BDD30A711");

                    b.ToTable("ESTADIO");
                });

            modelBuilder.Entity("Mundial2022.Entidades.JugEqCamp", b =>
                {
                    b.Property<string>("CJugador")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_JUGADOR")
                        .IsFixedLength(true);

                    b.Property<string>("CCampeonato")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_CAMPEONATO")
                        .IsFixedLength(true);

                    b.Property<string>("CEquipo")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("C_EQUIPO")
                        .IsFixedLength(true);

                    b.HasKey("CJugador", "CCampeonato")
                        .HasName("PK__JUG_EQ_C__473F0F2A39F92F5D");

                    b.HasIndex("CCampeonato");

                    b.HasIndex("CEquipo");

                    b.ToTable("JUG_EQ_CAMP");
                });

            modelBuilder.Entity("Mundial2022.Entidades.JugPartido", b =>
                {
                    b.Property<string>("CJugador")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_JUGADOR")
                        .IsFixedLength(true);

                    b.Property<int>("NroPartido")
                        .HasColumnType("int")
                        .HasColumnName("NRO_PARTIDO");

                    b.Property<string>("FAmonestado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("F_AMONESTADO")
                        .IsFixedLength(true);

                    b.Property<string>("FExpulsado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("F_EXPULSADO")
                        .IsFixedLength(true);

                    b.Property<string>("FGoleador")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("F_GOLEADOR")
                        .IsFixedLength(true);

                    b.Property<string>("NPosicion")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("N_POSICION");

                    b.Property<int>("NroCamiseta")
                        .HasColumnType("int")
                        .HasColumnName("NRO_CAMISETA");

                    b.HasKey("CJugador", "NroPartido")
                        .HasName("PK__JUG_PART__FE1852F59CB83388");

                    b.HasIndex("NroPartido");

                    b.ToTable("JUG_PARTIDO");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Jugador", b =>
                {
                    b.Property<string>("CJugador")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_JUGADOR")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("DNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("D_NACIMIENTO");

                    b.Property<string>("NJugador")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("N_JUGADOR");

                    b.HasKey("CJugador")
                        .HasName("PK__JUGADOR__D7CD63001DBBF6CA");

                    b.ToTable("JUGADOR");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Partido", b =>
                {
                    b.Property<int>("NroPartido")
                        .HasColumnType("int")
                        .HasColumnName("NRO_PARTIDO");

                    b.Property<string>("CCampeonato")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_CAMPEONATO")
                        .IsFixedLength(true);

                    b.Property<string>("CEquipo1")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("C_EQUIPO_1")
                        .IsFixedLength(true);

                    b.Property<string>("CEquipo2")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("C_EQUIPO_2")
                        .IsFixedLength(true);

                    b.Property<string>("CEstadioPart")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("C_ESTADIO_PART")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("DPartido")
                        .HasColumnType("date")
                        .HasColumnName("D_PARTIDO");

                    b.Property<string>("EPartido")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("E_PARTIDO");

                    b.Property<string>("NArbitro")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("N_ARBITRO");

                    b.Property<string>("NJuezLinea1")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("N_JUEZ_LINEA1");

                    b.Property<string>("NJuezLinea2")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("N_JUEZ_LINEA2");

                    b.Property<int?>("QGolesE1")
                        .HasColumnType("int")
                        .HasColumnName("Q_GOLES_E1");

                    b.Property<int?>("QGolesE2")
                        .HasColumnType("int")
                        .HasColumnName("Q_GOLES_E2");

                    b.HasKey("NroPartido")
                        .HasName("PK__PARTIDO__9D531F53021D8BA8");

                    b.HasIndex("CCampeonato");

                    b.HasIndex("CEquipo1");

                    b.HasIndex("CEquipo2");

                    b.HasIndex("CEstadioPart");

                    b.ToTable("PARTIDO");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Usuario", b =>
                {
                    b.Property<string>("UCodigo")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("U_CODIGO")
                        .IsFixedLength(true);

                    b.Property<string>("UApellido")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("U_APELLIDO");

                    b.Property<string>("UCorreo")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("U_CORREO");

                    b.Property<string>("UNombre")
                        .HasMaxLength(220)
                        .IsUnicode(false)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("U_NOMBRE");

                    b.Property<string>("UPassword")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("U_PASSWORD");

                    b.Property<int?>("UPuntosTotales")
                        .HasColumnType("int")
                        .HasColumnName("U_PUNTOS_TOTALES");

                    b.HasKey("UCodigo")
                        .HasName("PK__USUARIOS__E9817A8388322270");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("Mundial2022.Entidades.ApuestasUsuario", b =>
                {
                    b.HasOne("Mundial2022.Entidades.Partido", "NroPartidoNavigation")
                        .WithMany("ApuestasUsuarios")
                        .HasForeignKey("NroPartido")
                        .HasConstraintName("FK__APUESTAS___NRO_P__37A5467C")
                        .IsRequired();

                    b.HasOne("Mundial2022.Entidades.Usuario", "UCodigoNavigation")
                        .WithMany("ApuestasUsuarios")
                        .HasForeignKey("UCodigo")
                        .HasConstraintName("FK__APUESTAS___U_COD__38996AB5")
                        .IsRequired();

                    b.Navigation("NroPartidoNavigation");

                    b.Navigation("UCodigoNavigation");
                });

            modelBuilder.Entity("Mundial2022.Entidades.EquiposCampeonato", b =>
                {
                    b.HasOne("Mundial2022.Entidades.Campeonato", "CCampeonatoNavigation")
                        .WithMany("EquiposCampeonatos")
                        .HasForeignKey("CCampeonato")
                        .HasConstraintName("FK__EQUIPOS_C__C_CAM__398D8EEE")
                        .IsRequired();

                    b.HasOne("Mundial2022.Entidades.Equipo", "CEquipoNavigation")
                        .WithMany("EquiposCampeonatos")
                        .HasForeignKey("CEquipo")
                        .HasConstraintName("FK__EQUIPOS_C__C_EQU__3A81B327")
                        .IsRequired();

                    b.Navigation("CCampeonatoNavigation");

                    b.Navigation("CEquipoNavigation");
                });

            modelBuilder.Entity("Mundial2022.Entidades.JugEqCamp", b =>
                {
                    b.HasOne("Mundial2022.Entidades.Campeonato", "CCampeonatoNavigation")
                        .WithMany("JugEqCamps")
                        .HasForeignKey("CCampeonato")
                        .HasConstraintName("FK__JUG_EQ_CA__C_CAM__3B75D760")
                        .IsRequired();

                    b.HasOne("Mundial2022.Entidades.Equipo", "CEquipoNavigation")
                        .WithMany("JugEqCamps")
                        .HasForeignKey("CEquipo")
                        .HasConstraintName("FK__JUG_EQ_CA__C_EQU__3C69FB99");

                    b.HasOne("Mundial2022.Entidades.Jugador", "CJugadorNavigation")
                        .WithMany("JugEqCamps")
                        .HasForeignKey("CJugador")
                        .HasConstraintName("FK__JUG_EQ_CA__C_JUG__3D5E1FD2")
                        .IsRequired();

                    b.Navigation("CCampeonatoNavigation");

                    b.Navigation("CEquipoNavigation");

                    b.Navigation("CJugadorNavigation");
                });

            modelBuilder.Entity("Mundial2022.Entidades.JugPartido", b =>
                {
                    b.HasOne("Mundial2022.Entidades.Jugador", "CJugadorNavigation")
                        .WithMany("JugPartidos")
                        .HasForeignKey("CJugador")
                        .HasConstraintName("FK__JUG_PARTI__C_JUG__3E52440B")
                        .IsRequired();

                    b.HasOne("Mundial2022.Entidades.Partido", "NroPartidoNavigation")
                        .WithMany("JugPartidos")
                        .HasForeignKey("NroPartido")
                        .HasConstraintName("FK__JUG_PARTI__NRO_P__3F466844")
                        .IsRequired();

                    b.Navigation("CJugadorNavigation");

                    b.Navigation("NroPartidoNavigation");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Partido", b =>
                {
                    b.HasOne("Mundial2022.Entidades.Campeonato", "CCampeonatoNavigation")
                        .WithMany("Partidos")
                        .HasForeignKey("CCampeonato")
                        .HasConstraintName("FK__PARTIDO__C_CAMPE__403A8C7D");

                    b.HasOne("Mundial2022.Entidades.Equipo", "CEquipo1Navigation")
                        .WithMany("PartidoCEquipo1Navigations")
                        .HasForeignKey("CEquipo1")
                        .HasConstraintName("FK__PARTIDO__C_EQUIP__412EB0B6");

                    b.HasOne("Mundial2022.Entidades.Equipo", "CEquipo2Navigation")
                        .WithMany("PartidoCEquipo2Navigations")
                        .HasForeignKey("CEquipo2")
                        .HasConstraintName("FK__PARTIDO__C_EQUIP__4222D4EF");

                    b.HasOne("Mundial2022.Entidades.Estadio", "CEstadioPartNavigation")
                        .WithMany("Partidos")
                        .HasForeignKey("CEstadioPart")
                        .HasConstraintName("FK__PARTIDO__C_ESTAD__4316F928");

                    b.Navigation("CCampeonatoNavigation");

                    b.Navigation("CEquipo1Navigation");

                    b.Navigation("CEquipo2Navigation");

                    b.Navigation("CEstadioPartNavigation");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Campeonato", b =>
                {
                    b.Navigation("EquiposCampeonatos");

                    b.Navigation("JugEqCamps");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Equipo", b =>
                {
                    b.Navigation("EquiposCampeonatos");

                    b.Navigation("JugEqCamps");

                    b.Navigation("PartidoCEquipo1Navigations");

                    b.Navigation("PartidoCEquipo2Navigations");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Estadio", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Jugador", b =>
                {
                    b.Navigation("JugEqCamps");

                    b.Navigation("JugPartidos");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Partido", b =>
                {
                    b.Navigation("ApuestasUsuarios");

                    b.Navigation("JugPartidos");
                });

            modelBuilder.Entity("Mundial2022.Entidades.Usuario", b =>
                {
                    b.Navigation("ApuestasUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
